# A workflow to test the sdist that will be released to PyPI

name: sdist-test

on:
  workflow_dispatch:
    inputs:
      runs-on:
        description: 'OS to run on.'
        type: string
        default: 'ubuntu-latest'
      python-version:
        description: 'Python version to use.'
        type: string
        default: '3.11'

permissions: read-all

jobs:
  sdist-test:
    name: Test sdist
    runs-on:  ${{ inputs.runs-on }}
    timeout-minutes: 90

    steps:
      - name: Checkout Concordia
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871

      - name: Build source distribution
        run: python setup.py sdist

      - name: Set up Python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade setuptools
          pip install pytest-xdist

      - name: Install source distribution
        run: |
          pip install dist/*.tar.gz
          pip list

      - name: Test source distribution
        run: |
          pytest -n auto --pyargs concordia
